import Link from 'next/link';
import './global.css';
import { ProviderChakra } from './providers/app-chakra';

export const metadata = {
  title: 'Market PC Components',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-center h-14 w-full market_main_header">
          <ul className="flex gap-4 items-center ">
            <li>
              <Link href="./">Home</Link>
            </li>
            <li>
              <Link href="./">Categorías</Link>
            </li>
            <li>
              <Link href="./location">Ubicación</Link>
            </li>
            <li>
              <Link href="./contact">Contácto</Link>
            </li>
            <li>
              <Link href="./about">Sobre nosotros</Link>
            </li>
            <li>
              <Link href="./location">Ubicación</Link>
            </li>
          </ul>
        </header>
        <ProviderChakra>{children}</ProviderChakra>
      </body>
    </html>
  );
}
